### ISSUE TITLE
Languages files are not updated

### ISSUE THREAD

**Issue by floorfi** [NiciusB/vue-i18n-scanner#1]
I like the idea of your tool, unfortunately it does'nt work for me.

When I run the script, the language files are not getting updated, the content remains untouched (but the file date changes). The terminal output lists a couple of keys and gives no errors. Final statement is "No unsed keys!. 80 missing keys have been added to your language files".

If i clear the translation folder before starting the script, the files for the given languages are created, but do just contain an empty object "{}".

**Comment by NiciusB** [comment]
Hi! That's pretty weird. Sorry for the problems!
Can you share the command you're running, and the repo (if it's public)? That should help me reproduce the issue

**Comment by floorfi** [comment]
Hi,

unfortunately the repository is not public.

I was running the following command:
npx vue-i18n-scanner -v 'src' -l 'src/translation/locales' -f json -L 'en,de'

The list of keys in the terminal output seems fine. But every row has the information line: NaN, file; 'P' - if that helps:
![image](https://user-images.githubusercontent.com/44081410/89905382-67e34800-dbea-11ea-8b13-2161152aa24b.png)

The weirdest thing of course if, that the date of last change of the file gets modified, but no content gets changed.

**Comment by NiciusB** [comment]
There is definitely something wrong. I'll figure it out asap and ping you whenever it's fixed

**Comment by NiciusB** [comment]
Hey @floorfi can you try to use the new 1.0.2 release? I hadn't tested the tool on windows and it was breaking due to that.

I'm fairly confident it will work now, but there might still be some bug left to squish :p

**Comment by floorfi** [comment]
Perfect, that solved it. 
Thanks a lot!
